static_resources:
  listeners:
    - name: main-listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 50050 }
      # 50 MB to at least match ingress limit.
      per_connection_buffer_limit_bytes: 52428800
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                access_log:
                - name: envoy.file_access_log
                  config:
                    path: "/dev/stdout"
                stat_prefix: grpc_json
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: grpc-backend-services, timeout: { seconds: 60 } }
                http_filters:
                  - name: envoy.grpc_json_transcoder
                    config:
                      proto_descriptor: "/_descriptor/greeter.descriptor-set.binproto"
                      services:
                        - Greeter
                  - name: envoy.router
  clusters:
    - name: grpc-backend-services
      connect_timeout: 1.25s
      # 50 MB to at least match ingress limit.
      per_connection_buffer_limit_bytes: 52428800
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: grpc-backend-services
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: server
                    port_value: 50051
